services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG-16}
    hostname: ${PHOEBE_AIRFLOW_POSTGRES_HOST:-postgres}
    environment:
      - POSTGRES_USER=${PHOEBE_AIRFLOW_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${PHOEBE_AIRFLOW_POSTGRES_PASS:-postgres}
      - POSTGRES_DB=${PHOEBE_AIRFLOW_POSTGRES_DB:-postgres}
#    volumes:
#      - ${POSTGRES_DATA_DIR:-./postgresql_data}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PHOEBE_AIRFLOW_POSTGRES_USER:-postgres}" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - phoebe_net

  codbex-phoebe:
    build:
      context: ./
      no_cache: true
      tags:
        - ${PHOEBE_IMAGE-codbex-phoebe:dev}
    container_name: phoebe
    environment:
      - PHOEBE_AIRFLOW_POSTGRES_USER=${PHOEBE_AIRFLOW_POSTGRES_USER:-postgres}
      - PHOEBE_AIRFLOW_POSTGRES_PASS=${PHOEBE_AIRFLOW_POSTGRES_PASS:-postgres}
      - PHOEBE_AIRFLOW_POSTGRES_HOST=${PHOEBE_AIRFLOW_POSTGRES_HOST:-postgres}
      - PHOEBE_AIRFLOW_POSTGRES_DB=${PHOEBE_AIRFLOW_POSTGRES_DB:-postgres}
#      - PHOEBE_AIRFLOW_URL=https://httpbin.org # change Apache Airflow with httpbin for testing
    ports:
      - "80:80"
#      - "8080:8080" # expose Apache Airflow
    depends_on:
      - postgres
    networks:
      - phoebe_net

networks:
  phoebe_net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
