/*
 * Copyright (c) 2025 codbex or an codbex affiliate company and contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: 2025 codbex or an codbex affiliate company and contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getTemplate() {
	return {
		name: "Apache Airflow Starter",
		description: "Apache Airflow Starter Template",
		sources: [{
			location: "/template-airflow-starter/build-linux.sh",
			action: "generate",
			rename: "build-linux.sh"
		},{
			location: "/template-airflow-starter/build-mac.sh",
			action: "generate",
			rename: "build-mac.sh"
		},{
			location: "/template-airflow-starter/config/.empty",
			action: "generate",
			rename: "config/.empty"
		},{
			location: "/template-airflow-starter/plugins/.empty",
			action: "generate",
			rename: "plugins/.empty"
		},{
			location: "/template-airflow-starter/dags/example_dag.py.template",
			action: "generate",
            engine: "velocity",
            rename: "dags/{{fileName}}.py"
		},{
			location: "/template-airflow-starter/project.json",
			action: "generate",
			rename: "project.json"
		}],
		parameters: [{
			name: "dagId",
			label: "The id of the generated DAG"
		}],
		order: -200
	};
};
