services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG-13}
    container_name: postgres
    hostname: ${AIRFLOW_POSTGRES_HOST:-postgres}
    environment:
      - POSTGRES_USER=${AIRFLOW_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${AIRFLOW_POSTGRES_PASS:-postgres}
      - POSTGRES_DB=${AIRFLOW_POSTGRES_DB:-postgres}
#    volumes:
#      - ${POSTGRES_DATA_DIR:-./postgresql_data}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - airflow_net

  codbex-airflow:
    image: codbex-airflow:dev
    container_name: codbex-airflow
    environment:
      - AIRFLOW_POSTGRES_USER=${AIRFLOW_POSTGRES_USER:-postgres}
      - AIRFLOW_POSTGRES_PASS=${AIRFLOW_POSTGRES_PASS:-postgres}
      - AIRFLOW_POSTGRES_HOST=${AIRFLOW_POSTGRES_HOST:-postgres}
      - AIRFLOW_POSTGRES_DB=${AIRFLOW_POSTGRES_DB:-postgres}
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - airflow_net

networks:
  airflow_net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
