name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-pull-request.yaml@main
    with:
      platform-name: codbex-phoebe
      docker-build: true
    secrets: inherit
