name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0
      snapshot-version:
        description: Snapshot Version
        required: true
        default: 2.0.0-SNAPSHOT

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-release.yaml@main
    with:
      platform-name: codbex-phoebe
      maven-release: true
      release-version: ${{ inputs.release-version }}
      snapshot-version: ${{ inputs.snapshot-version }}
      docker-release: true
      release-content: |
        ## codbex-phoebe - ${{ inputs.release-version }}
        
        Phoebe is a Web IDE which allows you to write [Apache Airflow](https://airflow.apache.org/) application in an efficient way.
        
        ## Run steps
        
        ```
        docker run --name codbex-phoebe \
        --rm -p 80:80 \
        ghcr.io/codbex/codbex-phoebe:${{ inputs.release-version }}
        ```
        
        ## Access points:
        - [http://localhost:80](http://localhost:80) - Web IDE
        
        ## Default credentials:
        - user: `admin`
        - password: `admin`
    secrets: inherit
