name: Release - Platform

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 2.0.0
      snapshot-version:
        description: Snapshot Version
        required: true
        default: 3.0.0-SNAPSHOT

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/platform-release.yaml@main
    with:
      platform-name: codbex-phoebe
      maven-release: true
      release-version: ${{ inputs.release-version }}
      snapshot-version: ${{ inputs.snapshot-version }}
      docker-release: true
      upload-scanned-sarif-report: false
      release-content: |
        ## codbex-phoebe - ${{ inputs.release-version }}
        
        Phoebe is a Web IDE which allows you to write [Apache Airflow](https://airflow.apache.org/) applications in an efficient way.
        
        ## Run steps
        
        ### Start using Docker and released image
        
        #### Start PostgreSQL
        
          The instance which will be used for Airflow DB or used existing DB instance.
        
          ```shell
          export PHOEBE_AIRFLOW_POSTGRES_USER="postgres"
          export PHOEBE_AIRFLOW_POSTGRES_PASS="postgres"
          export PHOEBE_AIRFLOW_POSTGRES_DB="postgres"
        
          docker rm -f postgres
        
          docker run --name postgres \
            -e POSTGRES_PASSWORD="$PHOEBE_AIRFLOW_POSTGRES_PASS" \
            -e POSTGRES_USER="$PHOEBE_AIRFLOW_POSTGRES_USER" \
            -e POSTGRES_DB="$PHOEBE_AIRFLOW_POSTGRES_DB" \
            -p 5432:5432 \
            -d postgres:13
          ```
        
        #### Start Docker image
        
          ```shell
          export PHOEBE_IMAGE='ghcr.io/codbex/codbex-phoebe:${{ inputs.release-version }}'
        
          docker rm -f phoebe
        
          docker pull "$PHOEBE_IMAGE"
        
          docker run --name phoebe  \
            -p 80:80 \
            -e PHOEBE_AIRFLOW_POSTGRES_USER="$PHOEBE_AIRFLOW_POSTGRES_USER" \
            -e PHOEBE_AIRFLOW_POSTGRES_PASS="$PHOEBE_AIRFLOW_POSTGRES_PASS" \
            -e PHOEBE_AIRFLOW_POSTGRES_HOST="host.docker.internal" \
            -e PHOEBE_AIRFLOW_POSTGRES_DB="$PHOEBE_AIRFLOW_POSTGRES_DB" \
            $PHOEBE_IMAGE
          ```
        
        ## Access points:
        - [http://localhost:80](http://localhost:80) - Web IDE
        
        ## Default credentials:
        - user: `admin`
        - password: `admin`
    secrets: inherit
